GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjZhOGI4ZGU5MTNjZDMzNDUwZDUxMTM2ZiIsImlhdCI6MTc4NzUzMDgxMCwiZXhwIjoxNzg3NTM0NDEwfQ.fhFloSbkNBcBIzgzYLlhWffFfvlNY8t4YnW3q3ASzsI

{
  "title": "Test Title 1",
  "author": "user 1",
  "url": "hello",
  "likes": 6
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjZhODhjN2ZkMjg2ZjdiYzU5MTJiMjM2ZiIsImlhdCI6MTc4NzQzNzA2MX0.tvNNWf0-bpZTBFofTZtkEJlLR24CDEKefVhh-jz2Y14

{
  "title": "Test Title Signed 4",
  "author": "author A",
  "url": "hello",
  "likes": 6,
  "userId": "6a88c7fd286f7bc5912b236f"
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Title 2",
  "author": "author A",
  "url": "hello",
  "likes": 6,
  "userId": "6a88c7fd286f7bc5912b236f"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Title B",
  "author": "author B",
  "url": "hello",
  "likes": 7,
  "userId": "6a891a4261fe3766427febae"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Title C",
  "author": "author C",
  "url": "hello C",
  "likes": 8,
  "userId": "6a891a4261fe3766427febae"
}
###
DELETE http://localhost:3003/api/blogs/6a891a6961fe3766427febb0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjZhODhjN2ZkMjg2ZjdiYzU5MTJiMjM2ZiIsImlhdCI6MTc4NzQzNzA2MX0.tvNNWf0-bpZTBFofTZtkEJlLR24CDEKefVhh-jz2Y14
### Note: Token expires after 1 hour
DELETE http://localhost:3003/api/blogs/6a8a21a4581b8c934ba1ead6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2YTg5MWE0MjYxZmUzNzY2NDI3ZmViYWUiLCJpYXQiOjE3ODc1Mjk0ODksImV4cCI6MTc4NzUzMzA4OX0.GnaqmWsCvPJBiiLR64pDcOQe7Bw2-6aFeFOvRpMjYz4
