GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Title",
  "author": "author A",
  "url": "hello",
  "likes": 6,
  "userId": "6a88c7fd286f7bc5912b236f"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Title B",
  "author": "author B",
  "url": "hello",
  "likes": 7
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Title C",
  "author": "author C",
  "url": "hello C",
  "likes": 8
}