GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "user",
  "name": "user 1",
  "password": "password"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "user2",
  "name": "user 2",
  "password": "password"
}